# Generated by Django 2.1.4 on 2020-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('post_time', models.TimeField()),
                ('post_content', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('reply_id', models.CharField(max_length=20)),
                ('reply_content', models.CharField(max_length=240)),
                ('reply_time', models.TimeField()),
            ],
        ),
    ]
