# Generated by Django 2.1.4 on 2020-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_senti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_source',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_senti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_source',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_topic',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
