# Generated by Django 2.1.4 on 2020-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200223_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_senti',
            field=models.IntegerField(default=None),
        ),
    ]
