# Generated by Django 2.1.4 on 2020-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200223_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_senti',
            field=models.IntegerField(default=0),
        ),
    ]
