# Generated by Django 2.1.4 on 2020-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200223_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_senti',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_senti',
            field=models.IntegerField(null=True),
        ),
    ]
