# Generated by Django 2.1.4 on 2020-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200223_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_source',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_source',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
