# Generated by Django 2.1.4 on 2020-03-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20200226_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='process',
            field=models.IntegerField(default=0),
        ),
    ]
