# Generated by Django 2.1.4 on 2020-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20200325_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='url',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
