# Generated by Django 2.1.4 on 2020-03-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20200325_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attention',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='attention',
        ),
    ]
