# Generated by Django 2.1.4 on 2020-03-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('content', models.CharField(max_length=240)),
                ('source', models.IntegerField(default=0, null=True)),
                ('topic', models.CharField(default='1', max_length=20)),
                ('senti', models.IntegerField(null=True)),
                ('process', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
