# Generated by Django 2.1.4 on 2020-03-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
