# Generated by Django 2.1.4 on 2020-03-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_hole_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='url',
        ),
    ]
