# Generated by Django 2.1.4 on 2020-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_remove_hole_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('senti_value', models.IntegerField(default=0)),
                ('post_num', models.IntegerField(default=0)),
            ],
        ),
    ]
