# Generated by Django 2.1.4 on 2020-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20200416_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='neg_senti_value',
            field=models.IntegerField(default=0),
        ),
    ]
