# Generated by Django 2.1.4 on 2020-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_info_neg_senti_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='key_words',
            field=models.TextField(default=''),
        ),
    ]
