# Generated by Django 2.1.4 on 2020-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20200422_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='key_words',
            field=models.TextField(default=''),
        ),
    ]
